### ISSUE TITLE
Make the script more complete with information like overs etc.

### ISSUE THREAD

**Issue by neo1691** [neo1691/scorer.py#14]
Shailesh Gupta has given me an interesting peice of information over email.

Her says that we catn get the matchid from the description tag in the xml and use an url like this:
http://www.espncricinfo.com/netstorage/656493.json to get a json with complete information about the match. 

We can then add other important stats to the notification.

Anyone willing to give a look at it?

**Comment by srivallabh** [comment]
@neo1691 Can you please assign this enhancement to me?
I would like to work on this!

**Comment by neo1691** [comment]
Sure, still figuring out how to assign people on issues!!

**Comment by srivallabh** [comment]
@neo1691 Once you figureout if the contributors are capable to handle your brainchild code, You can take the critical issues to yourself and the rest to the guys who are capable!

**Comment by neo1691** [comment]
@srivallabh Checkout the comment above, I have updated the comment. Some issue with github.

**Comment by srivallabh** [comment]
@neo1691 Looks like you have to add them to the repo!
Please check this link.
https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by neo1691** [comment]
Done. Looking forward for you commit. Ideally it would be good if you can create a seperate function that processes interesting data from that json and then send it to the pop up notification function.

Also keep in mind that if the length of the string is more than certain bytes, then the notification won't show the message.

So You can use the title to show the score and then you can use the message parameter to show either the number of overs bowled or the runs scored by the batsmen etc. 

Thanks a lot for helping out.

**Comment by srivallabh** [comment]
@neo1691 I agree with your approach, I'll try to come up with something ASAP.

**Comment by neo1691** [comment]
Sure, India seems to be playing well. I hope we win!! Common India!!

**Comment by avinassh** [comment]
Great enhancement. I really love the way this project is heading, just from a simple Quora answer :smile:

**Comment by neo1691** [comment]
Exactly, I would have never thought I would be able to author my own project on github, do check out the todos that I have written on the README.md

**Comment by srivallabh** [comment]
@avinassh Your idea  on proxy is very refreshing.
@neo1691 Thanks for getting a group of coding enthusiasts into your project.
I will be creating PR with the JSON parsing soon.

**Comment by neo1691** [comment]
@srivallabh Sure, I am really excited now. Do check the todos! :)

**Comment by srivallabh** [comment]
For now, #18 Will satisfy this.
