### ISSUE TITLE
Re:workflow of the events in the fetching the code

### ISSUE THREAD

**Issue by kkvamsi** [neo1691/scorer.py#16]
HI,

I am new to Python and Github as well.:P

Request you to put up a flow of events(interactions) as I am planning to implement the functionality using JS and understand the present code in this project.

P.S.: I am unsure if i can put such requests in issues and found this a way to put up this request. EXCUSE ME for this.

**Comment by avinassh** [comment]
> Request you to put up a flow of events(interactions) 

What does this exactly mean? Did you mean to ask how script works?

**Comment by kkvamsi** [comment]
yes.what are the interactions that are made between client and server(cricinfo).
Secondly i wish to confirm if there is any usage of Cross site request here.
I am trying to use AJAX call but i am facing error .

**Comment by neo1691** [comment]
hi @kkvamsi this project right now is still very immature, just consists of a single file. So the flow is pretty simple. We send a request to a url which returns a simple xml, somewhere in the xml is the current score, so we use a python library to parse the xml and get the latest score, and then we use the score and use libnotify's python bindings to send a notification.

Just to make sure that there are no misinterpretations, the notifications are sent using a desktop library and not on any browser.

**Comment by kkvamsi** [comment]
So will the desktop library be using any calls similar to ajax? or is it totally different?

**Comment by avinassh** [comment]
Use any javascript api for libnotify. something like [this](http://mytrile.github.io/node-libnotify/) may be. You can use ajax to make repeated calls to Cricinfo. Parse the data and send that to notification api.

**Comment by kkvamsi** [comment]
@neo1691  with reference to your previous explaination,may I know how you are sending the request (protocol) to the URL which returns the XML?

**Comment by neo1691** [comment]
@kkvamsi I am send the request for the xml to get the live score

**Comment by surajssd** [comment]
@kkvamsi read here for python "requests" module http://docs.python-requests.org/en/latest/

**Comment by kkvamsi** [comment]
@surajssd thank you :)
