### ISSUE TITLE
Lot of hardcoding in the current version

### ISSUE THREAD

**Issue by neo1691** [neo1691/scorer.py#21]
The current version of latest score gets a lot of hardcoding. The code currently breaks when there is no international match going on live. 

The hardcoding in the json is the culprit. 

I have fixed the code partially, will release the stable version alongwith the proper code structure according to python standards.

**Comment by saurabh-deochake** [comment]
Hi, I realized today that current code has a lot of hardcoding. I was working on it today. But, later on got distracted by some other problems occurred. Especially, in Pynotify show method, we get gio.error "Connection is closed". 

I will work on removing hardcoding simultaneously with you.  The match URL is hardcoded too, I am working to remove it and make it more dynamic.

**Comment by neo1691** [comment]
Hi, @saurabh-deochake I have removed the hardcoding in my local code. I will publish my changes today. I am trying to restructure the code. 

Check it out once I publish it.

**Comment by saurabh-deochake** [comment]
Thanks @neo1691! Waiting for it.
