### ISSUE TITLE
ImportError after recent changes to app.py

### ISSUE THREAD

**Issue by nirmalvp** [neo1691/scorer.py#28]
Running python app.py : 

Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from scorer.system import exitApp
ImportError: No module named scorer.system

**Comment by neo1691** [comment]
Like I said in the commit messages. The way this script is run has been changed. From the root of the project, run `` python -m scorer ``

**Comment by nirmalvp** [comment]
Correct. Works fine with python -m scorer
