### ISSUE TITLE
Out of Index Error not handled for choices

### ISSUE THREAD

**Issue by kavirajk** [neo1691/scorer.py#3]
Code breakes if I choose any choice other than displayed one.

need to handle Out of Index Eror in https://github.com/neo1691/scorer.py/blob/master/scorer.py#L36-L38

**Comment by neo1691** [comment]
Thanks for reporting this. Should be an easy fix. Feel free to send me a pull request. Just make sure the indentation level is 4 tab space. Thank you.

**Comment by neo1691** [comment]
This has been fixed in #6 in the develop branch. I am yet to merge it with master.
