### ISSUE TITLE
Need help with setuptools:

### ISSUE THREAD

**Issue by neo1691** [neo1691/scorer.py#36]
I have made some changes to the structureCode branch and now I have added a setup.py to it. 

Doing ``python setup.py build`` build's the project and creates a build directory in the project root folder and ``sudo python setup.py install`` installs the project somewhere in the path of the system. 

But I have no idea how to run the app from anywhere else after installing. 

Someone with prior experience with setuptools might be able to help me out here. 

Thank you.

**Comment by adarshrao** [comment]
When I try to run "python setup.py build" from the terminal, I get the following error 

Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools

What am I doing incorrectly?

**Comment by neo1691** [comment]
@adarshrao Hi, thanks for trying it out. 
You need to install setuptools to use setup.py. There is a way in setuptools, wherein you place a 12KB .py file in your project and if your user does not have setuptools, setuptools can be installed automatically. I will place that file later in your project. 
For now you need to install setuptools on your machine. Which OS are you using? If you are on ubuntu/debian you can install it using ``sudo apt-get install python-setuptools``. 
Let me know which OS are you on?

**Comment by talatshaikh29** [comment]
@neo1691 As far as I know, it creates a dist folder in the current directory. That folder contains a zip file which contains the EGG file. I think you should modify your PATH variable to point it to the current directory. I think this might help


http://stackoverflow.com/questions/1264447/how-to-run-python-egg-files-directly-without-installing-them

**Comment by neo1691** [comment]
@talatshaikh29 Thanks a lot. Can you clone the latest version of the structureCode branch and test it on your machine with python2? If everything is wroking accordingly?

**Comment by adarshrao** [comment]
I'm on Ubuntu 14.04.  I managed to successfully install the setuptools module and also build setup.py. 

However, when I run "sudo python setup.py install", it goes on for a while before showing me this error. These are the last few lines. 

Installed /usr/local/lib/python2.7/dist-packages/scorer-0.1-py2.7.egg
Processing dependencies for scorer==0.1
Searching for requests
Reading https://pypi.python.org/simple/requests/
Download error on https://pypi.python.org/simple/requests/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'requests' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or download links found for requests
error: Could not find suitable distribution for Requirement.parse('requests')

Could you please tell me where I'm going wrong? This is my first time trying to run something on Github on my computer, please bear with me. Thanks.

**Comment by neo1691** [comment]
Hi @adarshrao , thanks for the info. To be honest, this is the first time I am trying to package a python script, and I don't know if the method that I am on still works or not. For time being I would suggest that you download the master version of scorer, which is one standalone script. 

Or else you can just do ``sudo apt-get install python-requests`` and ``sudo apt-get install python-bs4`` and then in the top level directory, you can run my script using ``python -m scorer``

**Comment by adarshrao** [comment]
Oh wait, I just managed to finish installing it. 

The problems were - 

1. I was unable to install pip. It kept saying "unable to locate package python-pip". I went into root terminal, used get-pip.py along with the proxy settings, that installed pip. 

The error remained still, so I then, ran "pip --proxy="[proxysettings]" install -r requirements.txt" from the root terminal and that installed everything else, I guess. 

Running sudo python setup.py install did it now and the final line was "Finished processing dependencies for scorer==0.1"

Uhm, how do I run the code now?

**Comment by neo1691** [comment]
HI, if you check the original question on this issue (which I have opened) it says the same. Even I am trying to figure out the same thing, how to use setup tools. 

By the way like I said if you want to run this app, just go the the root of the directory and run ``python -m scorer``

Make sure you are using python2

**Comment by neo1691** [comment]
Hi @talatshaikh29 @adarshrao and other developers. I have managed to package this script using setuptools. You can now install scorer using ``sudo python setup.py install``. This will create a binary called scorer which you can now call from anywhere on your command line. Just make sure you are using python2 to install scorer. 

I will merge the structureCode branch with master once I do some testing. I still need to figure out whether do I need to requirements.txt or not. 

Also I think I need to release the first version of scorer now. 

Thanks a lot.
