### ISSUE TITLE
Out of Index Error not handled while getting score from 'description' tag in 'develop' branch

### ISSUE THREAD

**Issue by kavirajk** [neo1691/scorer.py#4]
Out of Index Error not handled while getting score from 'description' tag in 'develop' branch. In case there is one active match. It returns out of index error. 
https://github.com/neo1691/scorer.py/blob/develop/scorer.py#L17-L18

**Comment by neo1691** [comment]
Hi, right now there is only one active match, and the code is not giving me an out of index error. You must have seen the code from quora. The develop branch was still having the earlier code, and I have updated it with the new code. 

Please have a look again in the develop branch.
